workflows:
  android-workflow:
    name: Android Debug APK
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - debug  # Nutzt den Standard Debug Keystore
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
