   workflows:
     android-workflow:
       name: Android Debug APK
       instance_type: mac_mini_m1
       environment:
         android_signing:
           - debug
       scripts:
         - name: Build APK
           script: ./gradlew assembleDebug
       artifacts:
         - app/build/outputs/**/*.apk
